[pytest]
filterwarnings =
    ignore:`torch_geometric.distributed` has been deprecated:DeprecationWarning
    ignore:`torch.jit.script` is deprecated:DeprecationWarning
    ignore:invalid value encountered in divide:RuntimeWarning:trimesh.triangles
